export const PACKAGE_NAME = "@sideline/core";

export * from "./scoring/score.js";
export * from "./scoring/rescore-projection.js";
export * from "./projections/base.js";
export * from "./projections/rest-of-season.js";
export * from "./projections/variance.js";
export * from "./projections/floor-ceiling.js";
export * from "./optimizer/eligibility.js";
export * from "./optimizer/solve.js";
export * from "./optimizer/locks.js";
export * from "./optimizer/availability.js";
export * from "./optimizer/recommend.js";
export * from "./matchup/defense-vs-position.js";
export * from "./matchup/multiplier.js";
export * from "./matchup/grade.js";
export * from "./matchup/config.js";
export * from "./trends/scoring-trend.js";
export * from "./trends/usage-trend.js";
export * from "./trends/consistency.js";
export * from "./trends/signal.js";
export * from "./trends/momentum.js";
